#! /usr/bin/env python3
import sys


class ManageUsersCLI(object):
    """
        Parser for commands to the manage_users library in a 'git' style.

        Argparse would be nice to use, but is extremely clunky for
        subcommands.
    """

    def __init__(self, config='/etc/manage_users.conf'):
        """
            Initialise the user management CLI.

            Keyword arguments:
            config -- Path to the config file for the CLI.
        """
        # Default program name, will be overridden when a command is run
        self.program_name = 'manuse'

        self.commands = {
            'list': {
                'func': self.list_users,
                'arguments': {
                    'example': {
                        'help': 'This does stuff.',
                        'values': ['a', 'b', 'c'],
                    },
                },
            },
            'create': {
                'func': self.create_user,
                'arguments': {
                    'example': {
                        'help': 'This does stuff.',
                        'values': ['a', 'b', 'c'],
                    },
                },
            },
            'sshkey': {
                'func': self.sshkey,
                'arguments': {
                    'example': {
                        'help': 'This does stuff.',
                        'values': ['a', 'b', 'c'],
                    },
                },
            },
            'modify': {
                'func': self.modify_user,
                'arguments': {
                    'example': {
                        'help': 'This does stuff.',
                        'values': ['a', 'b', 'c'],
                    },
                },
            },
            'configure': {
                'func': self.configure,
                'arguments': {
                    'example': {
                        'help': 'This does stuff.',
                        'values': ['a', 'b', 'c'],
                    },
                },
            },
        }

    def list_users(self):
        pass

    def create_user(self):
        pass

    def sshkey(self):
        pass

    def modify_user(self):
        pass

    def configure(self):
        pass

    def print_usage(self, output=sys.stdout, subcommand=None):
        """
            Provide usage for the CLI or a given subcommand.

            Keyword arguments:
            subcommand -- Help for a given subcommand.
        """
        # TODO: Actually implement this
        output.write('Here is how to use this.\n')

    def run_command(self, args):
        """
            Run a command based on args passed from the command line.

            Keyword arguments:
            args -- Arguments passed from the command line (sys.argv).
        """
        if len(args) < 2:
            sys.stderr.write('Not enough arguments.\n')
            self.print_usage(output=sys.stderr)
            sys.exit(1)

        self.program_name = args[0]


if __name__ == '__main__':
    cli = ManageUsersCLI()
    cli.run_command(sys.argv)
